Repository LSS-Manager/LSSM-V.4, pull requests merged in 2020-12, with the labels that each got.

#313 👷 Pushback to Github with Version Numbe
  build/push.sh
  package.json
  src/libraries.json
  src/modules/missionHelper/i18n/fr_FR.json
Labels: project

#336 🔀💚 improve build
  .eslintrc.json
  build/index.ts
  package.json
  scripts/index.ts
  src/LSSM-Menu.vue
  src/components/appstore.vue
  src/components/settings.vue
  src/core.ts
  src/globals.d.ts
  src/i18n.ts
  src/i18n/cs_CZ.ts
  src/i18n/de_DE.ts
  src/i18n/en_AU.ts
  src/i18n/en_GB.ts
  src/i18n/en_US.ts
  src/i18n/fr_FR.ts
  src/i18n/it_IT.ts
  src/i18n/nb_NO.ts
  src/i18n/nl_NL.ts
  src/modules/chatExtras/assets/timeFormatter.ts
  src/modules/clock/main.ts
  src/modules/extendedBuilding/assets/expansions.ts
  src/modules/extendedCallWindow/assets/generationDate.ts
  src/modules/missionHelper/settings.ts
  src/store.ts
  src/userscript.ts
  tsconfig.json
Labels: enhancement

#342 🌐 sv_SE | Small translations fixed
  src/i18n/sv_SE.ts
  src/modules/extendedCallWindow/i18n/sv_SE.root.json
  src/modules/overview/i18n/sv_SE.json
Labels: i18n
