Repository LSS-Manager/LSSM-V.4, pull requests merged in 2021-03, with the labels that each got.

#513 🔀 ✨ {alpha} redesign vehicle windows
  build/index.ts
  package.json
  src/components/enhanced-table.vue
  src/components/lightbox.vue
  src/mainpageCore.ts
  src/modules/dashboard/components/building-list.vue
  src/modules/generalExtensions/components/linkPreview.vue
  src/modules/lssmaql/lssmaql.vue
  src/modules/redesign/components/lightbox.vue
  src/modules/redesign/components/vehicle.vue
  src/modules/redesign/i18n/de_DE.json
  src/modules/redesign/main.ts
  src/modules/redesign/parsers/vehicle.ts
  src/modules/redesign/register.json
  src/modules/redesign/settings.ts
  src/modules/releasenotes/main.ts
  src/store.ts
  src/store/api.ts
  src/store/settings.ts
  src/userscript.ts
  static/lssm-v4.user.js
  typings/components/Lightbox.d.ts
  typings/modules/Redesign.d.ts
  typings/store/Actions.d.ts
  typings/store/api/Actions.d.ts
  typings/store/broadcast/Actions.d.ts
  typings/store/console/Actions.d.ts
  typings/store/event/Actions.d.ts
  typings/store/notifications/Actions.d.ts
  typings/store/settings/Actions.d.ts
  typings/store/storage/Actions.d.ts
Labels: enhancement

#536 🌐🇪🇸 [docs] first es_ES docs
  docs/es_ES/README.md
  docs/es_ES/apps.md
  docs/es_ES/appstore.md
  docs/es_ES/bugs.md
  docs/es_ES/error_report.md
  docs/es_ES/faq.md
  docs/es_ES/metadata.md
  docs/es_ES/other.md
Labels: documentation, i18n

#542 ✨ [redesign] toplist & updates
  src/components/enhanced-table.vue
  src/modules/redesign/components/coins/list.vue
  src/modules/redesign/components/credits.vue
  src/modules/redesign/components/credits/daily.vue
  src/modules/redesign/components/credits/list.vue
  src/modules/redesign/components/credits/overview.vue
  src/modules/redesign/components/lightbox.vue
  src/modules/redesign/components/toplist.vue
  src/modules/redesign/components/vehicle.vue
  src/modules/redesign/i18n/de_DE/credits/daily.json
  src/modules/redesign/i18n/de_DE/toplist.json
  src/modules/redesign/i18n/de_DE/vehicle/nextfms.json
  src/modules/redesign/main.ts
  src/modules/redesign/parsers/toplist.ts
  src/modules/redesign/parsers/vehicle/nextfms.ts
  src/modules/redesign/settings.ts
  typings/components/Enhanced-Table.d.ts
  typings/modules/Redesign.d.ts
Labels: enhancement

#564 🌐🇪🇦 more translations
  src/modules/extendedCallWindow/i18n/es_ES.js
  src/modules/extendedCallWindow/i18n/es_ES.root.json
  src/modules/generalExtensions/i18n/es_ES.json
  src/modules/generalExtensions/i18n/es_ES.root.json
  src/modules/hotkeys/i18n/es_ES.root.json
  src/modules/lssmaql/i18n/es_ES.root.json
  src/modules/missionHelper/i18n/es_ES.json
  src/modules/missionHelper/i18n/es_ES.root.json
  src/modules/notificationAlert/i18n/es_ES.json
  src/modules/notificationAlert/i18n/es_ES.root.json
  src/modules/overview/i18n/es_ES.json
  src/modules/overview/i18n/es_ES.root.json
  src/modules/releasenotes/i18n/es_ES.root.json
  src/modules/renameFz/i18n/es_ES.json
  src/modules/renameFz/i18n/es_ES.root.json
  src/modules/schoolingOverview/i18n/es_ES.json
  src/modules/schoolingOverview/i18n/es_ES.root.json
  src/modules/support/i18n/es_ES.root.json
  src/modules/telemetry/i18n/es_ES.root.json
  src/modules/template/i18n/es_ES.root.json
  src/modules/userid/i18n/es_ES.root.json
Labels: i18n
