Repository LSS-Manager/LSSM-V.4, pull requests merged in 2022-10, with the labels that each got.

#1809 🔀🚸 [redesign] fix untranslated string
  src/modules/redesign/components/vehicle.vue
  src/modules/redesign/i18n/de_DE/vehicle.json
  src/modules/redesign/i18n/en_AU/vehicle.json
  src/modules/redesign/i18n/en_GB/vehicle.json
  src/modules/redesign/i18n/en_US/vehicle.json
  src/modules/redesign/i18n/fr_FR/vehicle.json
  src/modules/redesign/i18n/it_IT/vehicle.json
  src/modules/redesign/i18n/nb_NO/vehicle.json
  src/modules/redesign/i18n/nl_NL/vehicle.json
  src/modules/redesign/i18n/pl_PL/vehicle.json
Labels: enhancement

#1810 🔀✨ [ge] map bookmarks: custom titles
  src/modules/generalExtensions/assets/mapMarkers.ts
Labels: hacktoberfest

#1817 🔀🌐 [so_Me] Add missing pois and fix colors
  src/i18n/cs_CZ.ts
  src/i18n/en_AU/buildings.ts
  src/i18n/en_GB/buildings.ts
  src/i18n/en_US/buildings.ts
  src/i18n/es_ES.ts
  src/i18n/fi_FI.ts
  src/i18n/it_IT.ts
  src/i18n/nb_NO.ts
  src/i18n/nl_NL.ts
Labels: hacktoberfest, hacktobertest-approved, hacktoberfest-accepted

#1818 🔀📝 [docs] update browser notes for Safari
  docs/cs_CZ/README.md
  docs/de_DE/README.md
  docs/en_GB/README.md
  docs/en_US/README.md
  docs/es_ES/README.md
  docs/fi_FI/README.md
  docs/fr_FR/README.md
  docs/it_IT/README.md
  docs/nb_NO/README.md
  docs/nl_NL/README.md
  docs/pl_PL/README.md
  docs/sv_SE/README.md
Labels: hacktoberfest, hacktobertest-approved, hacktoberfest-accepted

#1819 🔀Hotkeys
  docs/en_GB/contributing/committing.md
  docs/en_US/contributing/committing.md
  src/modules/hotkeys/assets/commands/building.ts
  src/modules/hotkeys/i18n/cs_CZ.root.json
  src/modules/hotkeys/i18n/de_DE.root.json
  src/modules/hotkeys/i18n/en_AU.root.json
  src/modules/hotkeys/i18n/en_GB.root.json
  src/modules/hotkeys/i18n/en_US.root.json
  src/modules/hotkeys/i18n/es_ES.root.json
  src/modules/hotkeys/i18n/fi_FI.root.json
  src/modules/hotkeys/i18n/fr_FR.root.json
  src/modules/hotkeys/i18n/nb_NO.root.json
  src/modules/hotkeys/i18n/nl_NL.root.json
  src/modules/hotkeys/i18n/pl_PL.root.json
  src/modules/hotkeys/i18n/sv_SE.root.json
  src/modules/hotkeys/main.ts
  src/modules/hotkeys/settings.ts
Labels: hacktoberfest, hacktobertest-approved, hacktoberfest-accepted

#1836 🔀✨ [build] let webpack know the build branch
  .eslintrc.json
  .github/workflows/build.yml
  build/build.sh
  build/index.ts
  scripts/createBuildScript.ts
  src/LSSM-Menu.vue
  src/globals.d.ts
  typings/LSSM-Menu.d.ts
Labels: enhancement

#1844 🔀[docs] FAQ=> LSSM status update
  docs/cs_CZ/faq.md
  docs/de_DE/faq.md
  docs/en_GB/faq.md
  docs/en_US/faq.md
  docs/es_ES/faq.md
  docs/fr_FR/faq.md
  docs/it_IT/faq.md
  docs/nb_NO/faq.md
  docs/nl_NL/faq.md
  docs/pl_PL/faq.md
  docs/sv_SE/faq.md
Labels: hacktoberfest, hacktobertest-approved

#1890 🌐[de_DE] docs update ladekreisel & debug mode
  docs/de_DE/settings.md
Labels: documentation

#1889 🔀🌐[fr_FR] Fix School and building and Update DOCS
  docs/fr_FR/settings.md
  src/i18n/fr_FR.ts
  src/i18n/fr_FR/buildings.ts
  src/modules/hotkeys/docs/fr_FR.md
  src/modules/hotkeys/i18n/fr_FR.root.json
  src/modules/statusCounter/docs/assets/fr_FR/settings.png
  src/modules/userid/docs/fr_FR.md
Labels: documentation

#1891 🔀 🐛 [hotkeys] fix #1812 uniqueness check
  src/components/setting/settings-appendable-list.vue
  src/modules/hotkeys/i18n/cs_CZ.root.json
  src/modules/hotkeys/i18n/de_DE.root.json
  src/modules/hotkeys/i18n/en_AU.root.json
  src/modules/hotkeys/i18n/en_GB.root.json
  src/modules/hotkeys/i18n/en_US.root.json
  src/modules/hotkeys/i18n/es_ES.root.json
  src/modules/hotkeys/i18n/fi_FI.root.json
  src/modules/hotkeys/i18n/fr_FR.root.json
  src/modules/hotkeys/i18n/nb_NO.root.json
  src/modules/hotkeys/i18n/nl_NL.root.json
  src/modules/hotkeys/i18n/pl_PL.root.json
  src/modules/hotkeys/i18n/sv_SE.root.json
  src/modules/hotkeys/settings.ts
  typings/Setting.d.ts
  typings/components/setting/AppendableList.d.ts
Labels: bug, ▲
