Repository LSS-Manager/LSSM-V.4, pull requests merged in 2022-06, with the labels that each got.

#1551 🇺🇲[ecw] add Foam Tanker to Water tanker
  src/modules/extendedCallWindow/i18n/en_US.js
Labels: i18n

#1557 🔀🔖 4.5.11
  .gitignore
  .whitesource
  .yarn/releases/yarn-3.2.1.cjs
  .yarnrc.yml
  build/build.sh
  docs/.vuepress/package.json
  docs/.vuepress/yarn.lock
  package.json
  scripts/index.ts
  src/i18n/fr_FR.ts
  src/i18n/fr_FR/buildings.ts
  src/i18n/it_IT.ts
  src/i18n/it_IT/buildings.ts
  src/i18n/nl_NL/buildings.ts
  src/libraries.json
  src/modules/asyncButtons/i18n/pl_PL.json
  src/modules/extendedCallList/assets/fixedEventInfo.ts
  src/modules/extendedCallList/i18n/cs_CZ.root.json
  src/modules/extendedCallList/i18n/de_DE.root.json
  src/modules/extendedCallList/i18n/en_AU.root.json
  src/modules/extendedCallList/i18n/en_GB.root.json
  src/modules/extendedCallList/i18n/en_US.root.json
  src/modules/extendedCallList/i18n/es_ES.root.json
  src/modules/extendedCallList/i18n/fr_FR.root.json
  src/modules/extendedCallList/i18n/it_IT.root.json
  src/modules/extendedCallList/i18n/nb_NO.root.json
  src/modules/extendedCallList/i18n/nl_NL.root.json
  src/modules/extendedCallList/i18n/pl_PL.root.json
  src/modules/extendedCallList/i18n/sv_SE.root.json
  src/modules/extendedCallList/main.ts
  src/modules/extendedCallList/settings.ts
  src/modules/extendedCallWindow/assets/moreReleasePatientButtons/mission.ts
  src/modules/extendedCallWindow/i18n/en_US.js
  src/modules/extendedCallWindow/i18n/it_IT.js
  src/modules/extendedCallWindow/i18n/it_IT.root.json
  src/modules/extendedCallWindow/i18n/pl_PL.js
  src/modules/extendedCallWindow/main.ts
  src/modules/extendedMap/assets/buildingComplexes.ts
  src/modules/extendedMap/components/buildingComplexes/buildingComplex.vue
  src/modules/extendedMap/components/buildingComplexes/settings.vue
  src/modules/extendedMap/i18n/de_DE.json
  src/modules/extendedMap/i18n/en_AU.json
  src/modules/extendedMap/i18n/en_GB.json
  src/modules/extendedMap/i18n/en_US.json
  src/modules/extendedMap/i18n/es_ES.json
  src/modules/extendedMap/i18n/fr_FR.json
  src/modules/extendedMap/i18n/it_IT.json
  src/modules/extendedMap/i18n/nb_NO.json
  src/modules/extendedMap/i18n/nl_NL.json
  src/modules/extendedMap/i18n/pl_PL.json
  src/modules/missionHelper/i18n/it_IT.json
  src/modules/redesign/components/profile.vue
  src/modules/redesign/components/vehicle.vue
  src/modules/redesign/parsers/vehicle.ts
  src/modules/releasenotes/main.ts
  src/modules/releasenotes/releasenotes.vue
  typings/api/AllianceInfo.d.ts
  typings/helpers.d.ts
  yarn.lock
Labels: ⬆ Version, ⬆ 4.5.x

#1490 🔀✨ [chatExtras] LightChatHistoryDesign
  src/modules/chatExtras/README.md
  src/modules/chatExtras/assets/lightDesignChatHistory.ts
  src/modules/chatExtras/docs/assets/de_DE/chat_light_design.png
  src/modules/chatExtras/docs/assets/de_DE/chat_light_design_redesign.png
  src/modules/chatExtras/docs/de_DE.md
  src/modules/chatExtras/i18n/cs_CZ.root.json
  src/modules/chatExtras/i18n/de_DE.root.json
  src/modules/chatExtras/i18n/en_AU.root.json
  src/modules/chatExtras/i18n/en_GB.root.json
  src/modules/chatExtras/i18n/en_US.root.json
  src/modules/chatExtras/i18n/es_ES.root.json
  src/modules/chatExtras/i18n/fr_FR.root.json
  src/modules/chatExtras/i18n/it_IT.root.json
  src/modules/chatExtras/i18n/nb_NO.root.json
  src/modules/chatExtras/i18n/nl_NL.root.json
  src/modules/chatExtras/i18n/pl_PL.root.json
  src/modules/chatExtras/i18n/sv_SE.root.json
  src/modules/chatExtras/main.ts
  src/modules/chatExtras/register.json
  src/modules/chatExtras/settings.ts
Labels: enhancement
