Repository LSS-Manager/LSSM-V.4, pull requests merged in 2023-07, with the labels that each got.

#2446 📝🇩🇪 [docs] Update LSSM on mobile
  docs/de_DE/faq.md
  docs/en_GB/faq.md
Labels: documentation

#2346 🔀[dev] add pre-commit package
  .husky/pre-commit
  build/build.sh
  package.json
  scripts/createBuildScript.ts
  yarn.lock
Labels: dependencies

#2484 🔀 [emv] en_US add K9 Carrier (large and small) to patrol car
  src/modules/extendedCallWindow/i18n/en_US.json
Labels: i18n
